### PR TITLE
Update with supported services

### PR DESCRIPTION
**Pull request by joelhans**
I think we need some place where we explain which collectors work with service discovery. Open to suggestions, but this feels like this best place for me.

### CODE REVIEW

**Comment by ilyam8** [comment]
> I think we need some place where we explain which collectors work with service discovery. 

Well, it depends on configuration, sd itself doesnt couple with a specific service.

We need to put the list to the [helmchart repo](https://github.com/netdata/helmchart#netdata-helm-chart-for-kubernetes-deployments).

It contains default configuration

> https://github.com/ilyam8/helmchart/tree/add_sd_to_nd_slave/sdconfig

Check this PR

> https://github.com/netdata/helmchart/pull/102

It adds sd container.

The list can be added as a part of that PR or a separate.

**Comment by ilyam8** [comment]
That list is a part of k8s install, which is our helmchart

**Comment by ilyam8** [comment]
> The list can be added as a part of that PR or a separate.

I think it makes sense to update that PR in the helmchart repo, i can copy paste the list, what do you think?

**Comment by joelhans** [comment]
> > The list can be added as a part of that PR or a separate.
> 
> I think it makes sense to update that PR in the helmchart repo, i can copy paste the list, what do you think?

If you think it makes more sense in the helmchart repo, let's move it there! You understand all these moving parts far better than I. I'm not even sure where it might belong in the helmchart README...

**Comment by ilyam8** [comment]
Ok, please remove in another commit the list, still there are some typos we need to fix.

**Pull request merged**
